In [1]:
import numpy as np

#Question 1

In [3]:
#Example 1
data1 = [6, 7.5, 8, 0, 1]
arr1= np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.ndim

2

In [6]:
arr2.shape

(2, 4)

In [7]:
arr1.dtype

dtype('float64')

In [8]:
arr2.dtype

dtype('int32')

In [9]:
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

In [10]:
arr4 = np.array([1, 2, 3], dtype=np.int32)
arr4

array([1, 2, 3])

In [11]:
#Example 2
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [12]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [14]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [15]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [17]:
#Example 3
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [18]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [20]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [21]:
#Example 4
arr = np.arange(10)
arr[5]

5

In [22]:
arr[5:8]

array([5, 6, 7])

In [23]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [24]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [25]:
arr2d[0][2]

3

In [26]:
arr2d[0, 2]

3

In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
#Example 5
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [31]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [33]:
arr2d[1, :2]

array([4, 5])

In [34]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [35]:
#Example 6
arr = np.arange(5)
arr * 4

array([ 0,  4,  8, 12, 16])

In [36]:
arr = np.random.randn(4, 3)
arr.mean(0)

array([ 0.11320341, -0.71988712, -0.40839061])

In [37]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.38271697, -0.41821861, -0.24238848],
       [-1.06560683,  0.68626257, -0.28614024],
       [ 0.40184413, -0.58354612,  1.26489982],
       [ 1.04647967,  0.31550216, -0.7363711 ]])

In [38]:
demeaned.mean(0)

array([ 0.00000000e+00, -2.77555756e-17, -2.77555756e-17])

In [39]:
row_means = arr.mean(1)
row_means.reshape((4, 1))


array([[-0.68613279],
       [-0.56018628],
       [ 0.02270783],
       [-0.1298212 ]])

In [40]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([1.85037171e-17, 0.00000000e+00, 3.70074342e-17, 7.40148683e-17])

In [41]:
#Example 7
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [42]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [43]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [44]:
#Example 8
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe','Joe'])
data = np.random.randn(7, 4)
names == 'Bob'
data[names == 'Bob']

array([[-0.14377603, -0.06083235,  0.98577097,  0.9565677 ],
       [-0.02400689, -1.22982088,  1.45584951,  1.86024062]])

In [45]:
data[names == 'Bob', 2:]

array([[0.98577097, 0.9565677 ],
       [1.45584951, 1.86024062]])

In [46]:
data[names == 'Bob', 3]

array([0.9565677 , 1.86024062])

In [47]:
names != 'Bob'
data[~(names == 'Bob')]

array([[ 0.17806258, -1.08672207,  1.11565578,  0.42920827],
       [ 1.39591112, -1.30146524, -0.02009334,  0.51014844],
       [-0.44370235, -0.72645918,  0.00795419,  0.07198469],
       [ 0.10063521,  0.46016966,  0.05982386,  1.31557692],
       [-0.9278864 ,  1.19784879,  0.14885598, -0.33008242]])

In [48]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-0.14377603, -0.06083235,  0.98577097,  0.9565677 ],
       [ 1.39591112, -1.30146524, -0.02009334,  0.51014844],
       [-0.02400689, -1.22982088,  1.45584951,  1.86024062],
       [-0.44370235, -0.72645918,  0.00795419,  0.07198469]])

In [49]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.98577097, 0.9565677 ],
       [0.17806258, 0.        , 1.11565578, 0.42920827],
       [1.39591112, 0.        , 0.        , 0.51014844],
       [0.        , 0.        , 1.45584951, 1.86024062],
       [0.        , 0.        , 0.00795419, 0.07198469],
       [0.10063521, 0.46016966, 0.05982386, 1.31557692],
       [0.        , 1.19784879, 0.14885598, 0.        ]])

In [50]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.17806258, 0.        , 1.11565578, 0.42920827],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.10063521, 0.46016966, 0.05982386, 1.31557692],
       [0.        , 1.19784879, 0.14885598, 0.        ]])

In [51]:
#Example 9
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [52]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [53]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [54]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [56]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [57]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [58]:
#Example 10
arr = np.arange(15).reshape((3, 5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 1.31213084,  0.53544166, -0.86320047],
       [ 0.53544166,  4.99175478,  4.05465513],
       [-0.86320047,  4.05465513,  8.24376891]])

In [60]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
arr.transpose((1, 0, 2))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [62]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [63]:
#Example 11
arr = np.arange(8)
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [64]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
#Example 12
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [72]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [74]:
arr = np.random.randn(5, 2)
first, second, third = np.split(arr, [1, 3])
first

array([[-0.8322351 , -0.21009371]])

In [75]:
second

array([[-0.45827492, -0.33506287],
       [ 1.49613098, -0.17232515]])

In [76]:
third

array([[-1.555706  ,  0.53991197],
       [ 0.07688748, -1.74875691]])

In [77]:
#Example 13
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [79]:
x = np.random.randn(8)
y =  np.random.randn(8)
x

array([ 0.72672454,  0.33724354,  1.01239196,  0.07538114,  1.08526281,
       -0.2927426 ,  0.93400279, -0.50751556])

In [80]:
y

array([ 0.02001268,  0.45983505,  0.7507513 , -0.79915929, -3.08425322,
       -0.43193877,  0.65200163, -2.89628161])

In [81]:
np.maximum(x, y) 

array([ 0.72672454,  0.45983505,  1.01239196,  0.07538114,  1.08526281,
       -0.2927426 ,  0.93400279, -0.50751556])

In [82]:
arr = np.random.randn(7) * 5
np.modf(arr)

(array([-0.27078786, -0.01112145,  0.11886053, -0.33095513, -0.50769982,
         0.25374497, -0.43228599]),
 array([ -4., -11.,   2.,  -4.,  -8.,   4.,  -1.]))

In [83]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [84]:
arr.sum()

45

In [85]:
arr = np.random.randn(5, 5)
arr[::2].sort(1) 
arr[:, :-1] < arr[:, 1:]


array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [86]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [87]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [88]:
arr = np.arange(3).repeat([1, 2, 2])
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [89]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17], dtype=int32)

In [90]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

In [91]:
#Example 14
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()


-0.1972445350422817

In [92]:
arr.sum()

-3.944890700845634

In [93]:
arr.sum(0)

array([-1.63718952, -1.99807042,  0.60907461, -0.91870537])

In [94]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [95]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [96]:
#Example 15
arr = np.random.randn(8)
arr.sort()

In [97]:
arr = np.random.randn(5, 3)
arr.sort(1)

In [98]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

-1.6701590394549293

In [99]:
#Example 16
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [100]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [101]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [102]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [103]:
#Example 17
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [104]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [105]:
x.dot(y) # equivalently np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [106]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [107]:
from numpy.linalg import inv, qr
X =  np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[   4.00438204,   20.27351284,  -46.30363503,  -58.61213649,
         -86.35924984],
       [  20.27351284,  148.79761289, -334.01665511, -424.03263509,
        -629.28078897],
       [ -46.30363503, -334.01665511,  751.00732504,  952.8733787 ,
        1413.9631584 ],
       [ -58.61213649, -424.03263509,  952.8733787 , 1209.9105546 ,
        1794.94615676],
       [ -86.35924984, -629.28078897, 1413.9631584 , 1794.94615676,
        2663.81067499]])

In [108]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -3.91411059e-14, -1.87541658e-13,
         1.50398111e-13,  3.27467954e-13],
       [-2.43776370e-14,  1.00000000e+00, -3.79944466e-13,
         1.39009141e-13, -3.96924481e-13],
       [ 1.61440140e-14, -3.10339300e-13,  1.00000000e+00,
         9.22966159e-13,  3.64997844e-13],
       [ 1.86578555e-14, -8.27642362e-14,  1.52527014e-13,
         1.00000000e+00, -2.53858812e-13],
       [ 1.68119666e-14,  1.22810678e-13, -9.32477073e-13,
        -4.83140417e-13,  1.00000000e+00]])

In [109]:
q, r = qr(mat)
r

array([[-4.86657848e+00, -7.10835909e+00, -4.79083468e+00,
        -5.26913743e+00,  4.25662046e+00],
       [ 0.00000000e+00, -6.79476426e+00,  8.34555017e-01,
         6.59722363e-01, -2.49282323e+00],
       [ 0.00000000e+00,  0.00000000e+00, -2.15007455e+00,
         1.60993580e+00,  5.64811839e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.82684929e+00,  1.23111749e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.80380974e-04]])

In [110]:
#Example 18
samples = np.random.normal(size=(4, 4))
samples

array([[-0.47448236,  0.22951432,  0.35104544, -0.14729172],
       [-0.53031259, -1.70175176,  0.02157904, -0.99708291],
       [-1.32022333, -0.53930433, -1.71369094,  1.0151881 ],
       [-0.11186186,  0.66309084, -0.85233595,  0.13473483]])

In [111]:
#Example 19
arr = np.arange(10)
np.save('some_array', arr)

In [112]:
np.savez('array_archive.npz', a=arr, b=arr)

In [113]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Question 2

In [114]:
 
data1=[1,3,9,12,18]
arr1=np.array(data1)
arr1

array([ 1,  3,  9, 12, 18])

In [115]:
data2=[[1,5,2,0],[3,6,4,7]]
arr2=np.array(data2)
arr2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

In [116]:
data3=[['7','6'],['5','4'],['3','2']]
arr3=np.array(data3)
arr3

array([['7', '6'],
       ['5', '4'],
       ['3', '2']], dtype='<U1')

In [117]:
data4=[[11,52,20,50],[34,61,43,17]]
arr4=np.array(data4)
arr4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

Question 3

In [118]:
sum_=np.add(data1,data1)
sum_

array([ 2,  6, 18, 24, 36])

In [119]:
mult=np.multiply(data1,10)
mult

array([ 10,  30,  90, 120, 180])

In [120]:
#Converting data type of data1
int1=arr1.astype(np.int32)
int1.dtype
#Converting data type of data1
int2=arr2.astype(np.int32)
int2.dtype
#Converting data type of data1
int3=arr3.astype(np.int32)
int3.dtype
#Converting data type of data1
int4=arr4.astype(np.int32)
int4.dtype

dtype('int32')

Question4

In [121]:

zeroArr=np.zeros((3,5))
zeroArr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [122]:
oneArr=np.ones((2,8))
oneArr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [123]:
randomArr=np.random.randint(20, size=(6, 3))
randomArr

array([[11, 13,  3],
       [ 8,  4, 15],
       [15, 12, 19],
       [ 3, 16,  5],
       [16,  1,  4],
       [ 8, 10, 15]])

Question 5

In [124]:

sqArr1=np.square(arr1[2:4])
sqArr1

array([ 81, 144], dtype=int32)

In [125]:
sqArr2=np.square([arr2[0][1],arr2[1][2]])
sqArr2

array([25, 16], dtype=int32)

Question 6

In [126]:
subjects=[['ML','OS','CCN'],['OS','AI','MP'],['CCN','ML','AI']]
subArr=np.array(subjects)
subArr[(subArr!='AI') & (subArr!='ML' )] = 0
subArr


array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

Question 7

In [127]:
transArr1=np.transpose(arr1)
transArr1


array([ 1,  3,  9, 12, 18])

In [128]:
transArr2=np.transpose(arr2)
transArr2

array([[1, 3],
       [5, 6],
       [2, 4],
       [0, 7]])

In [129]:
transArr3=np.transpose(arr3)
transArr3

array([['7', '5', '3'],
       ['6', '4', '2']], dtype='<U1')

In [130]:
transArr4=np.transpose(arr4)
transArr4

array([[11, 34],
       [52, 61],
       [20, 43],
       [50, 17]])

In [131]:
#Question 8
vstackConArr= np.vstack((arr2,arr4))
vstackConArr

array([[ 1,  5,  2,  0],
       [ 3,  6,  4,  7],
       [11, 52, 20, 50],
       [34, 61, 43, 17]])

In [132]:
hstackConArr= np.hstack((arr2,arr4))
hstackConArr

array([[ 1,  5,  2,  0, 11, 52, 20, 50],
       [ 3,  6,  4,  7, 34, 61, 43, 17]])

In [133]:
#Question 9
demeaned=arr2-arr2.mean(0)
demeaned

array([[-1. , -0.5, -1. , -3.5],
       [ 1. ,  0.5,  1. ,  3.5]])

In [134]:
#Question 10
reshapedArr=arr2.reshape((4,2))
reshapedArr

array([[1, 5],
       [2, 0],
       [3, 6],
       [4, 7]])

In [135]:
#Question 11
marks= [[60,40,70],[70,60,55],[50,80,65]]
marksArr=np.array(marks)
maxScore=np.max(marksArr,0)
maxScore

array([70, 80, 70])

In [11]:
import numpy as np
#Question 12
credit_hours=np.array([2,3,4])
sumOfCreditHours=np.add.reduce(credit_hours)

gradePoints=np.array([[2.0,0.0,3.0],[3.0,2.0,1.4],[1.0,3.7,4.0]])

summation=np.add.reduce(credit_hours * gradePoints,axis=1) #ROW ADDITION
CGPAarray=summation/sumOfCreditHours
CGPAarray


array([1.77777778, 1.95555556, 3.23333333])

In [139]:
print('CGPA of 3 students:')
for i in CGPAarray:
    print('CGPA : ',np.round(i,2))

CGPA of 3 students:
CGPA :  1.78
CGPA :  1.96
CGPA :  3.23


In [12]:
#Question 13
subjects=np.array([['ML','OS','CCN'],['OS','AI','MP'],['CCN','ML','AI']])
uniqueArr=np.unique(subjects)
uniqueArr

array(['AI', 'CCN', 'ML', 'MP', 'OS'], dtype='<U3')

In [17]:
# Question 14
my_array=np.random.normal(size=(4,4))
dot_Array=np.dot(my_array,my_array)
dot_Array

array([[-0.23528248,  0.50319884,  0.64682821,  0.75825989],
       [ 0.34530279,  1.96642871,  0.07097156,  0.72677464],
       [-0.69133082, -0.28968026,  0.85017082,  0.47009808],
       [-0.50849959,  2.90511034,  0.86499589,  1.25735916]])

In [15]:
inverted_Array=np.linalg.inv(my_array)
inverted_Array

array([[-0.15588998, -0.71831261, -0.53464055, -0.92891024],
       [-0.72545677,  0.16802475,  0.32608835, -0.03297396],
       [-0.38506769, -0.09357414, -0.55263904, -1.07127246],
       [ 0.93461254, -1.0278602 ,  1.12082809, -0.92181939]])

In [18]:
# Question 15
np.savez('array_archive.npz',a=dot_Array,b=inverted_Array)