In [2]:
import numpy as np

data1 = np.array([1,3,9,12,18])
data1

array([ 1,  3,  9, 12, 18])

In [3]:
data2 = np.array([[1, 5, 2, 0],[3, 6, 4, 7]])
data2

array([[1, 5, 2, 0],
       [3, 6, 4, 7]])

In [4]:
data3 = np.array([['7', '6'],['5', '4'], ['3', '2']])
data3

array([['7', '6'],
       ['5', '4'],
       ['3', '2']], dtype='<U1')

In [5]:
data4 = np.array([[11, 52, 20, 50], [34, 61, 43, 17]])
data4

array([[11, 52, 20, 50],
       [34, 61, 43, 17]])

In [6]:
answer_add = np.add(data1, data1)
answer_mul = np.multiply(data1, 10)
answer_add
answer_mul

array([ 10,  30,  90, 120, 180])

In [11]:
data1 = data1.astype('int64')
print("DATA 1: ", data1.dtype)
data2 = data2.astype('int64')
print("DATA 2: ", data2.dtype)
data3 = data3.astype('int64')
print("DATA 3: ", data3.dtype)
data4 = data4.astype('int64')
print("DATA 4: ", data4.dtype)

DATA 1:  int64
DATA 2:  int64
DATA 3:  int64
DATA 4:  int64


In [16]:
zero_array = np.zeros((3, 5))
ones_array = np.ones((2, 8))
random_array = np.random.randint(high=10, low=0, size=(6, 3))
print(zero_array)
print(ones_array)
print(random_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[8 0 3]
 [4 3 7]
 [6 2 7]
 [7 5 9]
 [6 6 7]
 [6 4 6]]
