In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv('iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

dataframe.innull()

In [20]:
inp = df.iloc[:,1:5]
inp

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [21]:
out = df.iloc[:,-1]
out

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [22]:
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier

from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [23]:
inp_train, inp_test, out_train, out_test= train_test_split(inp,out,test_size=0.2)

In [24]:
scaler=StandardScaler()
inp_train=scaler.fit_transform(inp_train)
inp_test=scaler.fit_transform(inp_test)

In [14]:
inp_test

array([[ 1.26745731,  0.21050066,  0.83926177,  0.60273096],
       [-0.74556312,  1.97870621, -0.95915631, -0.9272784 ],
       [-0.07455631, -0.54730172,  0.5994727 ,  0.32454744],
       [ 0.9319539 , -0.04210013,  0.53952543,  0.4636392 ],
       [-0.18639078, -0.54730172,  0.83926177,  1.29818976],
       [ 2.16213305, -0.04210013,  1.55862901,  1.71546504],
       [-0.96923206,  0.21050066, -1.19894539, -1.34455368],
       [-0.96923206, -1.55770489, -0.11989454, -0.09272784],
       [ 1.60296071, -0.04210013,  1.3787872 ,  0.74182272],
       [ 0.70828497, -0.29470093,  0.47957816,  0.32454744],
       [-0.74556312,  1.22090383, -1.25889266, -1.20546192],
       [-1.08106653,  0.96830304, -0.95915631, -1.20546192],
       [-0.29822525, -1.81030568,  0.29973635,  0.32454744],
       [-0.18639078, -1.3051041 ,  0.23978908,  0.04636392],
       [-0.18639078, -0.04210013,  0.35968362,  0.32454744],
       [-0.29822525, -1.55770489,  0.17984181,  0.04636392],
       [ 1.49112624, -0.

In [25]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(inp_train,out_train)

KNeighborsClassifier()

In [26]:
out_predict=knn.predict(inp_test)
print(metrics.accuracy_score(out_test,out_predict)*100)
print(confusion_matrix(out_test,out_predict))

86.66666666666667
[[12  0  0]
 [ 0  6  4]
 [ 0  0  8]]


In [ ]:
'''
1.Import dataset from csv into Dataframe
2.Data preprocessing
3.Data split into input and output
4.Data split into train and test
5.Data scaling
6.Train our model
7.Test our model

SKLEARN DOCUMENT READ.
'''